### ISSUE TITLE
Согласовать CSS  и HTMl  с дизайнером

### ISSUE THREAD

**Issue by o-dka** [o-dka/techBlog#2]
Когда согласовали, обновите эту проблему и тэгните меня!

**Comment by PussyHunter59** [comment]
@o-dka  очень близко к концу, скоро сделаем.

**Comment by o-dka** [comment]
Когда сделайте, напишите что делать и я создам проблемы

**Comment by PussyHunter59** [comment]
@o-dka можешь закрывать все согласовано.и тип и цвета блога в тз есть.

**Comment by o-dka** [comment]
Вы можете их сами закрывать
